# https://upptime.js.org/docs/configuration

owner: unnamed-dot-group
repo: upptime

sites:
  - name: unnamed.group
    url: https://unnamed.group
  - name: mastodon.unnamed.group
    url: https://mastodon.unnamed.group
  - name: uagpmc.com
    url: https://uagpmc.com
  - name: monsoonesports.org
    url: https://monsoonesports.org
  - name: monsoon.team
    url: https://monsoon.team
  - name: monsoon.academy
    url: https://monsoon.academy

assignees:
  - zuedev

status-website:
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/106413411
  favicon: https://avatars.githubusercontent.com/u/106413411
  theme: night
  css: "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap'); body { font-family: 'Inter' }"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
